name: flutter_animation_basic
description: Animationの学習です

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  timer_builder:
  freezed_annotation:
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  flutter_gen_runner:
  build_runner:
  freezed:
  json_serializable:

flutter:

  uses-material-design: true

  assets:
    - assets/
